version: "3.8"

services:
  postgres:
    container_name: students_container
    image: 'postgres:15-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_DB=students_admin
      - POSTGRES_PASSWORD=admin

